### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by joshepw** [tyeporter/Tomorrow-Night-Space-Gray#1]
What font did you use in the screenshoot?

**Comment by tyeporter** [comment]
Input Mono: https://input.fontbureau.com/
You can customize some of the letters by clicking the preview tab.

**Comment by joshepw** [comment]
Thanks Dude! I love this theme! ... I share my configuration file for a better look:
{
    "workbench.colorTheme": "Tomorrow Night - Space Gray",
    "editor.fontFamily": "Roboto Mono",
    "editor.fontSize": 14,
    "window.openFilesInNewWindow": "on",
    "terminal.integrated.fontFamily": "Roboto Mono for Powerline",
    "workbench.iconTheme": "ayu",
    "workbench.colorCustomizations": {
        "tab.activeBackground": "#2F3135",
        "activityBar.background": "#2F3135",
        "sideBar.background": "#2F3135",
        // "sideBar.border": "#252526",
        // "sideBarSectionHeader.border": "#252526",
        "sideBarSectionHeader.background": "#2F3135",
        "statusBar.background": "#8955A2",
        "statusBar.noFolderBackground": "#8955A2",
        "statusBar.debuggingBackground": "#8955A2",
        "terminal.ansiBlack": "#3A3E42",
        "terminal.ansiBlue": "#527289",
        "terminal.ansiBrightBlack": "#2F3236",
        "terminal.ansiBrightBlue": "#527289",
        "terminal.ansiBrightCyan": "#628F8B",
        "terminal.ansiBrightGreen": "#A1A54D",
        "terminal.ansiBrightMagenta": "#83638C",
        "terminal.ansiBrightRed": "#913530",
        "terminal.ansiBrightWhite": "#C4C7C4",
        "terminal.ansiBrightYellow": "#DEB250",
        "terminal.ansiCyan": "#628F8B",
        "terminal.ansiGreen": "#A1A54D",
        "terminal.ansiMagenta": "#83638C",
        "terminal.ansiRed": "#913530",
        "terminal.ansiWhite": "#C4C7C4",
        "terminal.ansiYellow": "#DEB250"
    },
    "git.autofetch": true,
    "editor.smoothScrolling": true,
    "terminal.integrated.enableBell": true,
    "breadcrumbs.enabled": true,
    "window.zoomLevel": 0,
    "explorer.confirmDelete": false,
    "git.enableSmartCommit": true,
    "terminal.integrated.rendererType": "dom",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "extensions.ignoreRecommendations": true,
    "explorer.confirmDragAndDrop": false,
    "editor.detectIndentation": false,
    "emmet.includeLanguages": {
        "twig": "html"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "editor.suggestSelection": "first",
    "emmet.triggerExpansionOnTab": true,
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "phpunit.files": "{test,tests}/**/*Test.php",
    "git.confirmSync": false,
    "[xml]": {
        "editor.defaultFormatter": "redhat.vscode-xml"
    },
    "workbench.tree.renderIndentGuides": "none",
    "emmet.excludeLanguages": [
        "markdown",
        "php"
    ],
    "php.format.codeStyle": "PHP Tools",
    "php.validate.run": "onType",
    "php.suggest.basic": false,
    "intelephense.completion.fullyQualifyGlobalConstantsAndFunctions": true,
    "intelephense.licenceKey": "00EXJXK6L8D56BU"
}

**Comment by tyeporter** [comment]
Glad ya like it 😀! Currently, I'm using a different theme that I am going to upload soon:

![code](https://user-images.githubusercontent.com/16263420/64056645-76ac2880-cb5a-11e9-8247-b5ca7d640ed8.png)
